# Generated by Django 5.2.7 on 2025-10-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Arts and Music'), ('industrial', 'Industrial Engineering'), ('health', 'Health & Wellness'), ('education', 'Education & Training'), ('travel', 'Travel & Tourism'), ('sports', 'Sports & Travel')], default='music', max_length=50),
        ),
    ]
